apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  secretname: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
  commonName: "it.actually.works"
  acme:
    config:
      - dns01:
          provider: cloud-dns
        domains:
          - "it.actually.works"
