steps:
  - name: "gcr.io/cloud-builders/npm"
    id: install
    dir: frontend
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    id: test
    dir: frontend
    args: ["test"]

  - name: "gcr.io/cloud-builders/npm"
    id: lint
    dir: frontend
    args: ["run", "lint"]
