# Azure pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    name: node:11-alpine
    id: translations
    dir: frontend
    entrypoint: npm
    args: ['run', 'check-translations']
  displayName: 'Run a multi-line script'
