steps:
- name: 'gcr.io/cloud-builders/npm'
  id: install
  args: ['install']
  dir: 'api'

- name: "arangodb/arangodb:3.3.19"
  id: arangodb
  env:
    - 'ARANGO_ROOT_PASSWORD=test'

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'api'
