version: "3.7"

services:
  minio:
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_BUCKET_NAME
    image: minio/minio
    command: server /data
    ports:
      - "9000"
    labels:
      - "traefik.backend=minio"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.entryPoints=minio"
      - "traefik.port=9000"
    volumes:
      - miniodata:/data
  arangodb:
    image: arangodb/arangodb:3.4.0
    environment:
      - ARANGO_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "8529"
    labels:
      - "traefik.backend=arangodb"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.entryPoints=arango"
      - "traefik.port=8529"
    volumes:
      - arangodata:/var/lib/arangodb3
  api:
    environment:
      - PORT=$API_PORT
      - DB_NAME
      - DB_URL
      - DB_USER
      - DB_PASSWORD
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_BUCKET_NAME
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3002"
    volumes:
      - ./api:/app
    command: npm start
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix:/graphql"
      - "traefik.frontend.entryPoints=http"
      - "traefik.port=3002"
  traefik:
    image: traefik:1.7
    command: --docker --api --entrypoints="Name:http Address::3000" --entrypoints="Name:arango Address::8529" --entrypoints="Name:minio Address::9000" --defaultentrypoints="Name:http,arango,minio"
    ports:
      - "3000:3000"
      - "8529:8529"
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    environment:
      - RAZZLE_PORT
      - RAZZLE_GOOGLE_ANALYTICS_ID
      - RAZZLE_SERVER_SIDE_API_URI
    ports:
      - "3000"
      - "3001:3001"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.entryPoints=http"
      - "traefik.port=3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
volumes:
  arangodata:
  miniodata:
