apiVersion: skaffold/v1
kind: Config
metadata:
  name: report-a-cybercrime
build:
  artifacts:
    - image: cybercrime-frontend
      context: f2
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: cybercrime-api
      context: api
      sync:
        infer:
          - "**/*.js"
deploy:
  kustomize:
    path: platform/overlays/minikube
