apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: symmorfosi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: symmorfosi
subjects:
  - kind: ServiceAccount
    name: default
    namespace: symmorfosi
