apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: symmorfosi
rules:
  - apiGroups:
      - ""
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - delete
      - watch
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
    verbs:
      - get
      - list
