apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cybercrime-frontend
  name: cybercrime-frontend
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cybercrime-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cybercrime-frontend
    spec:
      containers:
        - image: cdssnc/cybercrime-frontend
          imagePullPolicy: Always
          name: cybercrime-api
          env:
            - name: PORT
              value: '3000'
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
