apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: cybercrime-frontend-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: cybercrime-frontend
              servicePort: frontend-port
            path: /
