apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: todo-frontend
  name: todo-frontend
  namespace: default
  annotations:
    flux.weave.works/automated: 'true'
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - image: cdssnc/todo-frontend
          imagePullPolicy: Always
          name: todo-frontend
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
