version: 1
commandUpdated:
  generators:
    - command: kustomize build overlays/aks
  updaters:
    - containerImage:
        command: >-
          cd overlays/aks && kustomize edit set image "$FLUX_IMG:$FLUX_TAG"
