apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arangodb-claim
  namespace: cybercrime-api
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
