apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: arangodb-claim0
  name: arangodb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
status: {}
