---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cybercrime-api
  labels:
    app: cybercrime-api
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.cybercrime-api: glob:master-*
  name: cybercrime-api
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cybercrime-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cybercrime-api
    spec:
      initContainers:
        - image: cdssnc/cybercrime-arangoinit
          imagePullPolicy: Always
          name: cybercrime-arangoinit
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_NAME
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_PASSWORD
      containers:
        - image: acrrcmpcybercrime.azurecr.io/api
          imagePullPolicy: Always
          name: cybercrime-api
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_NAME
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cybercrime-api-secrets
                  key: DB_PASSWORD
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET_NAME
              value: reports
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
