---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cybercrime-frontend
  name: cybercrime-frontend
  namespace: cybercrime-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cybercrime-frontend
  template:
    metadata:
      labels:
        app: cybercrime-frontend
    spec:
      containers:
        - image: acrrcmpcybercrime.azurecr.io/frontend
          name: cybercrime-frontend
          env:
            - name: PORT
              value: "3000"
            - name: RAZZLE_SERVER_SIDE_API_URI
              value: http://cybercrime-api.cybercrime-api.svc.cluster.local:3000/graphql
            - name: RAZZLE_GOOGLE_ANALYTICS_ID
              value: "UA-130179934-1"
          resources: {}
