import { After, When, And, Then } from 'cypress-cucumber-preprocessor/steps'

When('I fill howdiditstart page forms in French', () => {
  cy.get('form')
    .find('[value="howDidTheyReachYou.email"]')
    .check({ force: true })
  cy.get('form').find('[id="email"]').type('suspectFrench@magma.com')
  cy.get('form')
    .find('[value="howDidTheyReachYou.phone"]')
    .check({ force: true })
  cy.get('form').find('[id="phone"]').type('1-800-000-0001')
  cy.get('form')
    .find('[value="howDidTheyReachYou.online"]')
    .check({ force: true })
  cy.get('form')
    .find('[id="online"]')
    .type('http://www.suspectFrenchAnonymous.com')
  cy.get('form').find('[value="howDidTheyReachYou.app"]').check({ force: true })
  cy.get('form')
    .find('[id="application"]')
    .type('noms d’applications où vous avez communiqué Application')
  cy.get('form')
    .find('[value="howDidTheyReachYou.others"]')
    .check({ force: true })
  cy.get('form').find('[id="others"]').type('Une publicité')
  cy.get('form').find('[id="startDay"]').type('19')
  cy.get('form').find('[id="startMonth"]').type('12')
  cy.get('form').find('[id="startYear"]').type('2019')
  cy.get('form')
    .find('[value="howManyTimes.severalTimes"]')
    .check({ force: true })
})
