import { After, When, And, Then } from 'cypress-cucumber-preprocessor/steps'

When('I fill howdiditstart page forms', () => {
  cy.get('form')
    .find('[value="howDidTheyReachYou.email"]')
    .check({ force: true })
  cy.get('form').find('[id="email"]').type('SuspectEnglish@magma.com')
  cy.get('form')
    .find('[value="howDidTheyReachYou.phone"]')
    .check({ force: true })
  cy.get('form').find('[id="phone"]').type('1-800-000-1111')
  cy.get('form')
    .find('[value="howDidTheyReachYou.online"]')
    .check({ force: true })
  cy.get('form').find('[id="online"]').type('http://www.suspectEnglish.com')
  cy.get('form').find('[value="howDidTheyReachYou.app"]').check({ force: true })
  cy.get('form').find('[id="application"]').type('Whatapps')
  cy.get('form')
    .find('[value="howDidTheyReachYou.others"]')
    .check({ force: true })
  cy.get('form').find('[id="others"]').type('In Person')
  cy.get('form').find('[id="startDay"]').type('26')
  cy.get('form').find('[id="startMonth"]').type('9')
  cy.get('form').find('[id="startYear"]').type('2019')
  cy.get('form')
    .find('[value="howManyTimes.severalTimes"]')
    .check({ force: true })
})
