import { When } from 'cypress-cucumber-preprocessor/steps'

When('I fill howdiditstart in French page forms', () => {
  cy.get('form')
    .find('[value="howDidTheyReachYou.email"]')
    .check({ force: true })
  cy.get('form').find('[name="email"]').type('suspectFrench@magma.com')
  cy.get('form')
    .find('[value="howDidTheyReachYou.phone"]')
    .check({ force: true })
  cy.get('form').find('[name="phone"]').type('1-800-000-0001')
  cy.get('form')
    .find('[value="howDidTheyReachYou.online"]')
    .check({ force: true })
  cy.get('form')
    .find('[name="online"]')
    .type('http://www.suspectFrenchAnonymous.com')
  cy.get('form')
    .find('[value="howDidTheyReachYou.application"]')
    .check({ force: true })
  cy.get('form')
    .find('[name="application"]')
    .type('noms d’applications où vous avez communiqué Application')
  cy.get('form')
    .find('[value="howDidTheyReachYou.others"]')
    .check({ force: true })
  cy.get('form').find('[name="others"]').type('Une publicité')
})
