apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
  name: arangodb-claim
  namespace: cybercrime-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
