bases:
- ../../base
patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- cybercrime-api-ingress.yaml
- arango-claim.yaml
- cybercrime-frontend-ingress.yaml
- traefik-ingress-controller-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: traefik
  newTag: "1.7"
resources:
- azure-storageclass.yaml
- eks-default-storageclass.yaml
secretGenerator:
- envs:
  - .env.arangodb
  name: arango-secrets
  namespace: cybercrime-api
- envs:
  - .env.api
  name: cybercrime-api-secrets
  namespace: cybercrime-api
- envs:
  - .env.minio
  files:
  - credentials.json
  name: minio-secrets
  namespace: cybercrime-api
