apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
    spec:
      containers:
        - args:
            - --kubernetes
            - --logLevel=DEBUG
            - --debug
            - --defaultentrypoints=http,https
            - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
            - --entrypoints=Name:https Address::443 TLS
            - --acme
            - --acme.onhostrule
            - --acme.entrypoint=https
            - --acme.domains=report-a-cybercrime.cdssandbox.xyz
            - --acme.email=mike.williamson@cds-snc.ca
            - --acme.storage=/certs/acme.json
            - --acme.httpchallenge
            - --acme.httpchallenge.entrypoint=http
            - --tracing=true
          image: traefik:1.7
          name: traefik-ingress-lb
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
            - containerPort: 443
              hostPort: 443
              name: https
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
          volumeMounts:
            - mountPath: /certs
              name: certs-claim
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: certs-claim
          persistentVolumeClaim:
            claimName: certs-claim
