apiVersion: batch/v1
kind: Job
metadata:
  name: sa-11-4
  namespace: symmorfosi
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        compliance: master
      restartPolicy: Never
      containers:
        - image: "cdssnc/github-reviews-check-compliance:latest"
          imagePullPolicy: Always
          name: "sa-11-4"
          env:
            - name: ORIGIN
              value: "cdssnc/github-reviews-check-compliance:latest"
            - name: COMPONENT
              value: "Infrastructure"
            - name: DESCRIPTION
              value: "The developers perform code review on application pull requests."
            - name: SATISFIES
              value: "SA-11,SA-11 (4)"
            - name: REPO_URL
              value: "https://github.com/cds-snc/report-a-cybercrime"
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
