apiVersion: batch/v1
kind: Job
metadata:
  name: sa-11-1-api
  namespace: symmorfosi
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        compliance: master
      restartPolicy: Never
      containers:
        - image: "cdssnc/url-check-compliance:latest"
          imagePullPolicy: Always
          name: "url-check-compliance-sa-11-1-api"
          env:
            - name: ORIGIN
              value: "cdssnc/url-check-compliance:latest"
            - name: COMPONENT
              value: "Source code"
            - name: DESCRIPTION
              value: "The application uses an ESLint file to do static code analysis in the API."
            - name: SATISFIES
              value: "SA-11,SA-11 (1)"
            - name: URL
              value: "https://github.com/cds-snc/report-a-cybercrime/blob/master/api/.eslintrc.js"
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sa-11-1-frontend
  namespace: symmorfosi
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        compliance: master
      restartPolicy: Never
      containers:
        - image: "cdssnc/url-check-compliance:latest"
          imagePullPolicy: Always
          name: "url-check-compliance-sa-11-1-frontend"
          env:
            - name: ORIGIN
              value: "cdssnc/url-check-compliance:latest"
            - name: COMPONENT
              value: "Source code"
            - name: DESCRIPTION
              value: "The application uses an ESLint file to do static code analysis in the front end."
            - name: SATISFIES
              value: "SA-11,SA-11 (1)"
            - name: URL
              value: "https://github.com/cds-snc/report-a-cybercrime/blob/master/frontend/.eslintrc.json"
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
