steps:
  - name: 'mikewilliamson/usesthis-ci'
    id: start_arangodb
    entrypoint: '/bin/sh'
    args: [
        '-c',
        "
        docker run -d --network=cloudbuild -p=8529:8529 --name=arangodb mikewilliamson/aci \
        && /wait-for arangodb:8529
        ",
      ]

  - name: node:11-alpine
    id: ci
    dir: api
    entrypoint: npm
    args: ['ci']
    env: ['HUSKY_SKIP_INSTALL=true']

  - name: node:11-alpine
    id: lint
    dir: api
    entrypoint: npm
    args: ['run', 'lint']

  - name: node:11-alpine
    dir: api
    entrypoint: npm
    args: ['run', 'coverage']
    env:
      - 'DB_NAME=$_DB_NAME'
      - 'DB_URL=$_DB_URL'
      - 'TEST_DB_URL=$_TEST_DB_URL'
      - 'DB_USER=$_DB_USER'
      - 'DB_PASSWORD=$_DB_PASSWORD'
      - 'MINIO_ACCESS_KEY=$_MINIO_ACCESS_KEY'
      - 'MINIO_SECRET_KEY=$_MINIO_SECRET_KEY'
      - 'MINIO_BUCKET_NAME=$_MINIO_BUCKET_NAME'

  - name: gcr.io/kaniko-project/executor:debug
    dir: 'api'
    args:
      - '--destination=gcr.io/$PROJECT_ID/api:$BRANCH_NAME-$SHORT_SHA'
      - '--destination=gcr.io/$PROJECT_ID/api:latest'
      - '--dockerfile=./Dockerfile'
      - '--reproducible'
      - '--cache=true'
      - '--cache-ttl=6h'
