name: Deploy Storybook

on:
  push:
    branches:
      - fix-storybook-deploy

jobs:
  deploy-storybook:
    name: Deploy storybook to GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        working-directory: f2
        run: npm install
        env:
          CI: true
      - name: deploy
        working-directory: f2
        run: npm run deploy-storybook -- --ci
